# Generated by Django 5.2.4 on 2025-07-25 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopproducts',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
