# Generated by Django 5.2.4 on 2025-07-25 05:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopproducts',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='shop.category'),
            preserve_default=False,
        ),
    ]
