# Generated by Django 5.2.4 on 2025-07-25 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_shopproducts_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default=1, max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
