# Generated by Django 5.2.4 on 2025-07-18 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('client', 'Client'), ('trainer', 'Trainer')], default='client', max_length=10),
        ),
    ]
