# Generated by Django 5.2.4 on 2025-07-19 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0004_alter_customuser_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='experience_years',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='hourly_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='location',
            field=models.IntegerField(choices=[(0, 'Yellow Dream'), (1, 'Purple Dream'), (2, 'BlockBuster')], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='specialization',
            field=models.IntegerField(choices=[(0, 'Strength Training'), (1, 'Yoga & Flexibility'), (2, 'Cardio & Endurance'), (3, 'CrossFit'), (4, 'Bodybuilding'), (5, 'Rehabilitation & Injury Recovery'), (6, 'Personal Nutrition Coaching')], default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customuser',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
