# Generated by Django 5.2.4 on 2025-07-19 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0005_customuser_experience_years_customuser_hourly_rate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='specialization',
            field=models.IntegerField(blank=True, choices=[(0, 'Strength Training'), (1, 'Yoga & Flexibility'), (2, 'Cardio & Endurance'), (3, 'CrossFit'), (4, 'Bodybuilding'), (5, 'Rehabilitation & Injury Recovery'), (6, 'Personal Nutrition Coaching')], null=True),
        ),
    ]
