# Generated by Django 5.2.4 on 2025-07-19 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0006_alter_customuser_specialization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='location',
            field=models.IntegerField(blank=True, choices=[(0, 'Yellow Dream'), (1, 'Purple Dream'), (2, 'BlockBuster')], null=True),
        ),
    ]
