# Generated by Django 5.2.4 on 2025-07-19 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0007_alter_customuser_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='free',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='hourly_rate',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=8, null=True),
        ),
    ]
