# Generated by Django 5.2.4 on 2025-07-19 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0008_customuser_free_alter_customuser_hourly_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='free',
            field=models.BooleanField(default=True),
        ),
    ]
