# Generated by Django 5.2.4 on 2025-07-21 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0011_alter_customuser_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='hourly_rate',
            new_name='price',
        ),
    ]
