# Generated by Django 5.2.4 on 2025-07-23 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0012_rename_hourly_rate_customuser_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('client', 'Client'), ('trainer', 'Trainer'), ('gym', 'Gym')], default='client', max_length=10),
        ),
    ]
