# Generated by Django 5.2.4 on 2025-07-23 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0013_alter_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profit',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
