# Generated by Django 5.2.4 on 2025-07-23 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0014_customuser_profit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profit',
            field=models.IntegerField(default=0),
        ),
    ]
