# Generated by Django 5.2.4 on 2025-07-13 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listofgyms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gym',
            name='location',
            field=models.IntegerField(choices=[(0, 'Yellow Dream'), (1, 'Purple Dream'), (2, 'BlockBuster')]),
        ),
        migrations.AddField(
            model_name='gym',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Locations',
        ),
    ]
