# Generated by Django 5.2.4 on 2025-07-13 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listofgyms', '0002_alter_gym_location_gym_description_delete_locations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workingtime',
            name='day',
        ),
    ]
