# Generated by Django 5.2.4 on 2025-07-13 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listofgyms', '0003_remove_workingtime_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gym',
            name='slug',
            field=models.SlugField(blank=True),
        ),
        migrations.AlterField(
            model_name='gym',
            name='title',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
