# Generated by Django 5.2.4 on 2025-07-20 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listofgyms', '0004_alter_gym_slug_alter_gym_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='gym',
            name='image',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
