# Generated by Django 5.2.4 on 2025-07-21 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listofgyms', '0006_gym_latitude_gym_longitude_alter_gym_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gym',
            name='latitude',
            field=models.FloatField(auto_created=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='gym',
            name='location',
            field=models.IntegerField(blank=True, choices=[(0, 'River Mall'), (1, 'ТРЦ Gulliver'), (2, 'Retroville'), (3, 'Ocean Plaza'), (4, 'SkyMall'), (5, 'Blockbuster Mall'), (6, 'Prospekt Mall'), (7, 'Cosmo Multimall'), (8, 'Karavan'), (9, 'Epicenter'), (10, 'ЕПІЦЕНТР'), (11, 'Epitsentr K'), (12, 'DREAM berry'), (13, 'Gorodok Shopping Mall'), (14, 'Silver Breeze'), (15, 'Darynok'), (16, 'DREAM yellow'), (17, 'Ukraina Shopping Mall'), (18, 'ТРЦ “РайON”'), (19, 'Epitsentr')], null=True),
        ),
        migrations.AlterField(
            model_name='gym',
            name='longitude',
            field=models.FloatField(auto_created=True, max_length=500),
        ),
    ]
