# Generated by Django 5.2.4 on 2025-07-21 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listofgyms', '0007_alter_gym_latitude_alter_gym_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gym',
            name='latitude',
            field=models.FloatField(auto_created=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='gym',
            name='longitude',
            field=models.FloatField(auto_created=True, max_length=50),
        ),
    ]
