# Generated by Django 5.2.4 on 2025-07-21 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listofgyms', '0008_alter_gym_latitude_alter_gym_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='gym',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
