# Generated by Django 5.2.4 on 2025-07-23 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listofgyms', '0010_subscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='start_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
