# Generated by Django 5.2.4 on 2025-07-22 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='service_name',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='membership_type',
            field=models.CharField(choices=[('membership', 'Monthly Membership'), ('personal_training', 'Personal Training')], default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderitem',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
