# Generated by Django 5.2.4 on 2025-07-23 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_email_order_first_name_order_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='membership_type',
            field=models.CharField(max_length=50),
        ),
    ]
